[package]
name = "git-tutorial"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.0"
structopt = "0.3.26"
rsa = "0.6.1"
hex = "0.4.3"
regex = "1.5.5"